[RP2350_DEBUG_SERVER]
debug_server = 
    C:\Program Files\SEGGER\JLink\JLinkGDBServerCL
    -nohalt
    -nologtofile
    -endian 
    little
    -if
    SWD
    -speed
    4000
    -select
    USB
    -port
    2331
    -device
    RP2350_M33_0

;
; global custom
;
[custom]
build_flags =
  -D LOGICMODULE
  ; add OPENKNX_WATCHDOG normal only in releases and not here
  -D OPENKNX_WATCHDOG
  ; -D OPENKNX_DEBUGGER
  -D OPENKNX_LOOPTIME_WARNING=100
  ; -D DEBUG_TP_FRAMES
  ; -D OPENKNX_DUALCORE
  -D OPENKNX_OVERRIDE_MASK_VERSION=0x07B0

[custom_develop]
extends = custom
build_flags =
  ${custom.build_flags}
  -D OPENKNX_HEARTBEAT
  -D OPENKNX_DEBUG
  ; -D OPENKNX_DEBUGGER
  ; -D OPENKNX_RUNTIME_STAT
  ; -D OPENKNX_RUNTIME_STAT_BUCKETN=7
  ; "-D OPENKNX_RUNTIME_STAT_BUCKETS=100, 200, 500, 1000, 2000, 5000"
  ; -D OPENKNX_HEARTBEAT_PRIO
  ; -D OPENKNX_RTT
  ; -D BUFFER_SIZE_UP=10240
  ; -D LOGIC_TRACE
  ; ; to see trace logs, they must match one of the 5 filters (TRACE_LOG1 .. TRACE_LOG2)
  ; "-D OPENKNX_TRACE1=Meter.*"
  ; "-D OPENKNX_TRACE1=Common.*"
  ; "-D OPENKNX_TRACE1=Button.*"
  ; "-D OPENKNX_TRACE2=Flash.*"
  ; "-D OPENKNX_TRACE3=DummyChannel<1>"
  ; "-D OPENKNX_TRACE4=DummyChannel<[3-5]>"

[custom_debug]
debug_build_flags = 
  ${OPENKNX_DEBUG.build_flags}
  -D OPENKNX_HEARTBEAT
  -D OPENKNX_DEBUGGER
  -D OPENKNX_WAIT_FOR_SERIAL=5000
  -O0  
  -ggdb3 

[custom_releases]
extends = custom
build_flags =
  ${custom.build_flags}

; RP2040
[RP2040_custom]
extends = RP2040, custom
#platform = https://github.com/maxgerhardt/platform-raspberrypi.git
build_flags =
  -D SERIAL_DEBUG=Serial
  -D USE_KNX_DMA_UART=0
  -D USE_KNX_DMA_IRQ=0
  -Wunused-variable
debug_build_flags =
  ${custom_debug.debug_build_flags}
  ; -D DEBUG_TP_FRAMES

[env:develop_RP2040]
extends = RP2040_develop, RP2040_custom, custom_develop, RP2040_EXCHANGE_16MB
build_flags =
  ${KNX_TP.build_flags}
  ${RP2040_develop.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_develop.build_flags}
  ${RP2040_EXCHANGE_16MB.build_flags}
  ; -D DEVICE_REG1_BASE_V1
  ; -D DEVICE_REG1_SEN_MULTI
  -D DEVICE_PIPICO_BCU_CONNECTOR
  ; -D SML_TEST_STRINGS


[env:develop_RP2040_JLINK]
extends = env:develop_RP2040, UPLOAD_JLINK


; ESP32
[ESP32_custom]
extends = ESP32, custom
build_flags =
  -D SERIAL_DEBUG=Serial
  -I lib/OGM-HardwareConfig/include
  -D OPENKNX_USB_EXCHANGE_IGNORE
  -D OPENKNX_LED_TIME=info3Led
  -D OPENKNX_OVERRIDE_MASK_VERSION=0x07B0
debug_build_flags =
  ${custom_debug.debug_build_flags}


; --- S3 base mirrors [ESP32] but with the S3 board ---
[ESP32_s3]
extends = BASE, ESP32_8MB
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32-s3-devkitc-1-n4r2
framework = arduino
board_build.filesystem = littlefs
lib_ldf_mode = chain
extra_scripts =
  lib/OGM-Common/scripts/pio/prepare.py
  lib/OGM-Common/scripts/pio/create_esp32_image.py
build_flags =
  ${BASE.build_flags}
  -D BOARD_HAS_PSRAM
monitor_filters =
  esp32_exception_decoder
  ${env.monitor_filters}
debug_build_flags =
  ${ESP32_custom.debug_build_flags}


; S3 develop profile (like [ESP32_develop] but S3)
; ESP32-s3
[custom_ESP32_s3]
extends = custom
monitor_filters = esp32_exception_decoder
build_flags =
  -D SERIAL_DEBUG=Serial      ; Use Serial (FTDI on pins 44/43) for debug output
  -D KNX_FLASH_CALLBACK
  -D HVAC_DEBUG
build_unflags =
  -D LWIP_DONT_PROVIDE_BYTEORDER_FUNCTIONS

[custom_release_ESP32_s3]
extends = custom
monitor_filters = esp32_exception_decoder
build_flags =
  -D SERIAL_DEBUG=Serial      ; Use Serial (FTDI on pins 44/43) for debug output
  -D KNX_FLASH_CALLBACK
build_unflags =
  -D LWIP_DONT_PROVIDE_BYTEORDER_FUNCTIONS



[env:release_BOARD_ESP32S3_XIAO]
extends = ESP32_releases, ESP32_custom, ESP32_8MB
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
; platform = espressif32
board = seeed_xiao_esp32s3
build_flags =
  ${KNX_IP.build_flags}
  ${ESP32_releases.build_flags}
  ${ESP32_custom.build_flags}
  ${custom_releases.build_flags}
  -D OKNXHW_OPENKNXIAO_ESP32S3_V1_COMMON
  -D KNX_IP_WIFI
  ; -D CONFIG_ETH_ENABLED #only for ESP32
debug_build_flags =
  ${ESP32_custom.debug_build_flags}


[env:develop_ESP32_WIP]
extends = ESP32_develop, ESP32_custom, custom_develop, ESP32_8MB, ESP32_UPLOAD_USB
build_flags =
  ${KNX_IP.build_flags}
  ${ESP32_develop.build_flags}
  ${ESP32_custom.build_flags}
  ${custom_develop.build_flags}
  -D DEVICE_UP1_WLAN_2XUART
  -D KNX_IP_WIFI
  ; -D CONFIG_ETH_ENABLED
  ;-D OPENKNX_DUALCORE
board = seeed_xiao_esp32s3
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip


[custom_release_ESP32]
extends = ESP32_releases
build_flags =
  ${KNX_IP.build_flags}
  ${ESP32_custom.build_flags}
  ${ESP32_releases.build_flags}
  -D KNX_IP_WIFI
  ; ${custom.build_flags}
 


[board_OKNXHW_OPENKNXIAO_ESP32S3_MINI_V1_USB]
extends = ESP32_8MB
build_flags =
  -D OKNXHW_OPENKNXIAO_ESP32S3_MINI_V1
board = seeed_xiao_esp32s3
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip

[env:release_OKNXHW_OPENKNXIAO_ESP32S3_MINI_V1]
extends = custom_release_ESP32, ESP32_8MB, board_OKNXHW_OPENKNXIAO_ESP32S3_MINI_V1_USB
build_flags =
   ${custom_release_ESP32.build_flags}  
   ${board_OKNXHW_OPENKNXIAO_ESP32S3_MINI_V1_USB.build_flags}




;*******************************************************
; Releases - for all devices
[env:release_DEVICE_REG1_LAN_TP_Base]
extends = ESP32_releases, ESP32_custom, ESP32_8MB
build_flags =
  ${KNX_IP.build_flags}
  ${ESP32_releases.build_flags}
  ${ESP32_custom.build_flags}
  ${custom_releases.build_flags}
  -D DEVICE_REG1_LAN_TP_BASE
  -D KNX_IP_LAN
  ; -D CONFIG_ETH_ENABLED #only for ESP32
debug_build_flags =
  ${ESP32_custom.debug_build_flags}


[env:release_DEVICE_REG1_BASE_V0]
extends = RP2040_releases, RP2040_custom, RP2040_EXCHANGE_16MB
build_flags =
  ${KNX_TP.build_flags}
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_releases.build_flags}
  ${RP2040_EXCHANGE_16MB.build_flags}
  -D DEVICE_REG1_BASE_V0
debug_build_flags =
  ${RP2040_custom.debug_build_flags}

[env:release_DEVICE_REG1_BASE]
extends = RP2040_releases, RP2040_custom, RP2040_EXCHANGE_16MB
build_flags =
  ${KNX_TP.build_flags}
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_releases.build_flags}
  ${RP2040_EXCHANGE_16MB.build_flags}
  -D DEVICE_REG1_BASE
debug_build_flags =
  ${RP2040_custom.debug_build_flags}

[env:release_DEVICE_PIPICO_BCU_CONNECTOR]
extends = RP2040_releases, RP2040_custom, RP2040_EXCHANGE_2MB
build_flags =
  ${KNX_TP.build_flags}
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_releases.build_flags}
  ${RP2040_EXCHANGE_2MB.build_flags}
  -D DEVICE_PIPICO_BCU_CONNECTOR
debug_build_flags =
  ${RP2040_custom.debug_build_flags}

[env:release_DEVICE_SEN_UP1_8XTH]
extends = RP2040_releases, RP2040_custom, RP2040_EXCHANGE_16MB
build_flags =
  ${KNX_TP.build_flags}
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_releases.build_flags}
  ${RP2040_EXCHANGE_16MB.build_flags}
  -D DEVICE_SEN_UP1_8XTH
debug_build_flags =
  ${RP2040_custom.debug_build_flags}

[env:release_DEVICE_REG1_SEN_MULTI]
extends = RP2040_releases, RP2040_custom, RP2040_EXCHANGE_16MB
build_flags =
  ${KNX_TP.build_flags}
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_releases.build_flags}
  ${RP2040_EXCHANGE_16MB.build_flags}
  -D DEVICE_REG1_SEN_MULTI
debug_build_flags =
  ${RP2040_custom.debug_build_flags}

[env:release_DEVICE_SMARTMF_1TE_BE_3CH]
extends = RP2040_releases, RP2040_custom, RP2040_EXCHANGE_16MB
build_flags =
  ${KNX_TP.build_flags}
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_releases.build_flags}
  ${RP2040_EXCHANGE_16MB.build_flags}
  -D DEVICE_SMARTMF_1TE_BE_3CH
debug_build_flags =
  ${RP2040_custom.debug_build_flags}

[env:release_DEVICE_SMARTMF_2SML_3BE]
extends = RP2040_releases, RP2040_custom, RP2040_EXCHANGE_16MB
build_flags =
  ${KNX_TP.build_flags}
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_releases.build_flags}
  ${RP2040_EXCHANGE_16MB.build_flags}
  -D DEVICE_SMARTMF_2SML_3BE
debug_build_flags =
  ${RP2040_custom.debug_build_flags}

[env:release_DEVICE_SMARTMF_1TE_REG]
extends = RP2040_releases, RP2040_custom, RP2040_EXCHANGE_16MB
build_flags =
  ${KNX_TP.build_flags}
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_releases.build_flags}
  ${RP2040_EXCHANGE_16MB.build_flags}
  -D DEVICE_SMARTMF_1TE_REG
debug_build_flags =
  ${RP2040_custom.debug_build_flags}

[env:release_DEVICE_SMARTMF_SENSORMODUL]
extends = RP2040_releases, RP2040_custom, RP2040_EXCHANGE_16MB
build_flags =
  ${KNX_TP.build_flags}
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_releases.build_flags}
  ${RP2040_EXCHANGE_16MB.build_flags}
  -D DEVICE_SMARTMF_SENSORMODUL
debug_build_flags =
  ${RP2040_custom.debug_build_flags}

[env:release_DEVICE_SMARTMF_REALPRESENCE_V2]
extends = RP2040_releases, RP2040_custom, RP2040_EXCHANGE_16MB
build_flags =
  ${KNX_TP.build_flags}
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_releases.build_flags}
  ${RP2040_EXCHANGE_16MB.build_flags}
  -D DEVICE_SMARTMF_REALPRESENCE_V2
debug_build_flags =
  ${RP2040_custom.debug_build_flags}

[env:release_DEVICE_REG2_PIPICO_V1_DD_METER]
extends = RP2040_releases, RP2040_custom, RP2040_EXCHANGE_2MB
build_flags =
  ${KNX_TP.build_flags}
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_releases.build_flags}
  ${RP2040_EXCHANGE_2MB.build_flags}
  -D DEVICE_REG2_PIPICO_V1_DD_METER
debug_build_flags =
  ${RP2040_custom.debug_build_flags}


[env:release_DEVICE_REG1_BASE_IP]
extends = RP2040_releases, RP2040_custom, RP2040_EXCHANGE_16MB
build_flags =
  ${KNX_IP.build_flags}
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_releases.build_flags}
  ${RP2040_EXCHANGE_16MB.build_flags}
  -D DEVICE_REG1_BASE_IP
  -D KNX_IP_LAN
debug_build_flags =
  ${RP2040_custom.debug_build_flags}

[env:release_DEVICE_AB_BUT_GIR]
extends = RP2040_releases, RP2040_custom, RP2040_EXCHANGE_16MB
build_flags =
  ${KNX_TP.build_flags}
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_releases.build_flags}
  ${RP2040_EXCHANGE_16MB.build_flags}
  -D DEVICE_AB_BUT_GIR
debug_build_flags =
  ${RP2040_custom.debug_build_flags}


; legacy devices
[env:release_PresenceMultiSensor_ABSmartHouse]
extends = RP2040_releases, RP2040_custom, RP2040_EXCHANGE_16MB
build_flags =
  ${KNX_IP.build_flags}
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_releases.build_flags}
  ${RP2040_EXCHANGE_16MB.build_flags}
  -D DEVICE_AB_PRE
debug_build_flags =
  ${RP2040_custom.debug_build_flags}

[env:release_PresenceMR16_ABSmartHouse]
extends = RP2040_releases, RP2040_custom, RP2040_EXCHANGE_16MB
build_flags =
  ${KNX_IP.build_flags}
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_releases.build_flags}
  ${RP2040_EXCHANGE_16MB.build_flags}
  -D DEVICE_AB_PRE_MR16
debug_build_flags =
  ${RP2040_custom.debug_build_flags}

[env:release_PresenceWall_ABSmartHouse]
extends = RP2040_releases, RP2040_custom, RP2040_EXCHANGE_16MB
build_flags =
  ${KNX_IP.build_flags}
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_releases.build_flags}
  ${RP2040_EXCHANGE_16MB.build_flags}
  -D DEVICE_AB_PRE_WALL
debug_build_flags =
  ${RP2040_custom.debug_build_flags}

[env:release_AB_TouchRound_RP2350]
extends = RP2350_custom_releases, RP2040_custom, RP2040_EXCHANGE_16MB
board = rpipico2
build_flags =
  ${KNX_TP.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_releases.build_flags}
  ${RP2040_releases.build_flags}
  ${RP2040_EXCHANGE_16MB.build_flags}
  -D BOARD_AB_TOUCH_ROUND_RP2350
debug_build_flags =
  ${RP2040_custom.debug_build_flags}

