#pragma once

#define MAIN_Version "809e870"
#define KNX_Version "2.2.2+ee3c00e"
#define MODULE_FileTransferModule_Version "0.1.4+3a96b4e"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 4
#define MODULE_FileTransferModule_ETS 1
#define MODULE_Common_Version "1.5.1+193e462"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 5
#define MODULE_Common_Version_Revision 1
#define MODULE_Common_ETS 21
#define MODULE_LogicModule_Version "3.8.0+ea7c433"
#define MODULE_LogicModule_Version_Major 3
#define MODULE_LogicModule_Version_Minor 8
#define MODULE_LogicModule_Version_Revision 0
#define MODULE_LogicModule_ETS 56
#define MODULE_Network_Version "0.5.4+70804df"
#define MODULE_Network_Version_Major 0
#define MODULE_Network_Version_Minor 5
#define MODULE_Network_Version_Revision 4
#define MODULE_Network_ETS 5
#define MODULE_UsbExchange_Version "0.0.2+42daf08"
#define MODULE_UsbExchange_Version_Major 0
#define MODULE_UsbExchange_Version_Minor 0
#define MODULE_UsbExchange_Version_Revision 2
#define MODULE_UsbExchange_ETS 0
