#pragma once

#define MAIN_Version "d24ff87"
#define KNX_Version "2.1.2+ed9a913"
#define MODULE_LogicModule_Version "3.6.0+39db4ad"
#define MODULE_LogicModule_Version_Major 3
#define MODULE_LogicModule_Version_Minor 6
#define MODULE_LogicModule_Version_Revision 0
#define MODULE_LogicModule_ETS 54
#define MODULE_Common_Version "1.3.0+cb13927"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 3
#define MODULE_Common_Version_Revision 0
#define MODULE_Common_ETS 19
#define MODULE_HardwareConfig_Version "1.0.0+f10eafb"
#define MODULE_HardwareConfig_Version_Major 1
#define MODULE_HardwareConfig_Version_Minor 0
#define MODULE_HardwareConfig_Version_Revision 0
#define MODULE_HardwareConfig_ETS 16
#define MODULE_FileTransferModule_Version "0.1.0+ac39398"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 0
#define MODULE_FileTransferModule_ETS 1
#define MODULE_UsbExchange_Version "0.0.1+6e49286"
#define MODULE_UsbExchange_Version_Major 0
#define MODULE_UsbExchange_Version_Minor 0
#define MODULE_UsbExchange_Version_Revision 1
#define MODULE_UsbExchange_ETS 0
#define MODULE_Network_Version "0.4.0+29a0563"
#define MODULE_Network_Version_Major 0
#define MODULE_Network_Version_Minor 4
#define MODULE_Network_Version_Revision 0
#define MODULE_Network_ETS 4
