# Check build of OpenKNX OAM (merging/building of OpenKNX knxprod for combination of all referenced module versions + build of full releases)
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2024-2025 Cornelius Koepp

name: oam-check
run-name: Check OAM Build

on: [push]

jobs:
  check:
    name: Check '${{ matrix.target }}' (${{ matrix.restore_branch && 'branch' || 'commit' }})
    strategy:
      fail-fast: false
      matrix:

        # [BUILD]: all build targets
        target:
          - "Release"
          - ""
          - "IP"
          - "IP-dev"

        # [REF]: same commit and (newest on) branch
        restore_branch:
          # TODO check: building on commit will fail, on dependencies.txt creation
          # - false
          - true

    uses: ./.github/workflows/openknx-oam-check.yml
    with:
      KNXPROD_PREFIX: Logikmodul
      target: ${{ matrix.target }}
      restore_branch: ${{ matrix.restore_branch }}